Develop
kajikaji0725/ToDo-App pull request #4
Opened 2021-09-08 10:07 UTC by kajikaji0725

2021-09-08 10:31 UTC, earlgray283 requested changes
ちょっと多めだけど、半分ぐらいは相談なので

2021-09-08 10:31 UTC, earlgray283 commented on pkg/http.go
> +var homeworks []*Homework
todo-app のバックエンドだったら struct の名前は Todo が適切では？

2021-09-08 10:31 UTC, earlgray283 commented on pkg/http.go
> +	var setHomework Homework
一般に prefix が動詞な命名は関数にすることが多いからここでは普通に homework で良さそう

2021-09-08 10:31 UTC, earlgray283 commented on pkg/http.go
>  		http.Error(w, "json parsing error", 400)
あー、ごめん
400 よりも `http.StatusBadRequest` 使った方がいいかも(const 値)

2021-09-08 10:31 UTC, earlgray283 commented on pkg/http.go
>  		http.Error(w, "json parsing error", 400)
http ステータスコードは http パッケージ内に定数として定義されてるからそれを使った方がいい(使わなくてもやってることは同じだけど)

2021-09-08 10:31 UTC, earlgray283 commented on pkg/http.go
> +var homeworks []*Homework
あと、Homework のポインタのスライスって json に変えられたっけ？

2021-09-08 10:31 UTC, earlgray283 commented on pkg/http.go
> +	id := vars["id"]
id が存在しなかったときのエラーハンドリング

って思ったけど、mux ってパスパラメーターがないときはマッチしない？

2021-09-08 10:31 UTC, earlgray283 commented on pkg/http.go
>  	fmt.Fprintln(w, "Not Found\nMaybe you input the wrong key.")
http.StatusBadRequest を返すのが適切かも

2021-09-08 10:31 UTC, earlgray283 commented on pkg/http.go
> +	var updateHomework Homework
ここも関数名と混同するから普通に homework でいいと思う

2021-09-08 10:31 UTC, earlgray283 commented on pkg/http.go
> -	router.HandleFunc("/homework", getAllHomework).Methods("GET")
todo-app なのでエンドポイントも /todo/ の方が適切かと・・。

2021-09-08 10:31 UTC, earlgray283 commented on pkg/http.go
>  	router.HandleFunc("/", rootPage)
多分テスト用に作ったと思うけど、いらないエンドポイントは削除したほうがコンパクトかも

2021-09-08 10:31 UTC, earlgray283 commented on pkg/http.go
>  func StartServer() *mux.Router {
*mux.Router を返す関数だから NewRouter() の方が適切？

2021-09-08 10:31 UTC, earlgray283 commented on pkg/http.go
> +var homeworks []*Homework
また、各ハンドラで生成された Homework の変数をポインタとしてグローバルな homeworks に持たせておくのは良くない気がする。普通に []Homework として Homework をコピーして持たせるならいいんだけど、そうでないなら古い変数が永遠にメモリに残り続けてしまってメモリ管理的に嬉しくなさそう。

2021-09-08 10:35 UTC, kajikaji0725 commented on pkg/http.go
> +	id := vars["id"]
マッチしないね

2021-09-08 10:36 UTC, kajikaji0725 commented on pkg/http.go
> -	router.HandleFunc("/homework", getAllHomework).Methods("GET")
そうなのか。
/todoだと何してるかわからないかなって思って

2021-09-08 10:40 UTC, kajikaji0725 commented on pkg/http.go
>  	router.HandleFunc("/", rootPage)
どこのこと？

2021-09-08 10:44 UTC, earlgray283 commented on pkg/http.go
> -	router.HandleFunc("/homework", getAllHomework).Methods("GET")
todo リストだからね

2021-09-08 10:44 UTC, earlgray283 commented on pkg/http.go
>  	router.HandleFunc("/", rootPage)
`router.HandleFunc("/", rootPage)`

2021-09-08 10:44 UTC, earlgray283 commented on pkg/http.go
> +	id := vars["id"]
404?

2021-09-08 10:54 UTC, kajikaji0725 commented on pkg/http.go
> +var homeworks []*Homework
今やってるやつの場合だと、逐次新しいメモリのところにHomeworkが使われちゃうって感じ？

2021-09-08 10:56 UTC, kajikaji0725 commented on pkg/http.go
> +	id := vars["id"]
あ、存在しないときか
localhost:8080/homework/は404になるけど、localhost:8080/homework/（存在しないid）は404にはならない

2021-09-08 10:57 UTC, kajikaji0725 commented on pkg/http.go
>  	router.HandleFunc("/", rootPage)
それっていらないの？

2021-09-08 10:58 UTC, kajikaji0725 commented on pkg/http.go
>  	router.HandleFunc("/", rootPage)
ホーム画面として使うのかと思った

2021-09-08 11:02 UTC, earlgray283 commented on pkg/http.go
>  	router.HandleFunc("/", rootPage)
あくまで api サーバーだからね
必要なものだけあればいい

2021-09-08 11:02 UTC, earlgray283 commented on pkg/http.go
> +	id := vars["id"]
なるほどー、じゃあ id の存在をチェックしなくてもいいのね、了解

2021-09-08 11:08 UTC, earlgray283 commented on pkg/http.go
> +var homeworks []*Homework
端的に言えばメモリの無駄遣いだね
[]*Homework のポインタを保持するための分と、そのポインタが示す値の分が必要になる。[]Homework にすれば append するときに Homework のコピーが生成されてそれが []Homework の中に入るから、必要なメモリは []Homework の Homework を保持するための分だけで済む。
まあ確かに []*Homework でポインタにした方がパフォーマンスは良くなるんだけど、サーバーは実行時間が非常に長いからパフォーマンスよりもリソースの方を大切にしたほうがいいんじゃないかなと。

2021-09-09 06:34 UTC, earlgray283 commented on pkg/http.go
> +	var updatehomework Homework
updatehomework だと関数名のように聞こえるので updatedHomework で形容詞的に使えば適切かと

2021-09-09 06:35 UTC, earlgray283 commented
あと、今のままだとサーバーが死んだら保持している todo データが全てなくなるので `todos.json` に保存できた方が嬉しいね

2021-09-24 16:39 UTC, earlgray283 reviewed
思想が含まれている可能性がある

2021-09-24 16:39 UTC, earlgray283 commented on docker-compose.yml
> +      - CRYPTO_KEY=passw0rdpassw0rdpassw0rdpassw0rd
これどこで使ってる？

2021-09-24 16:39 UTC, earlgray283 commented on main.go
> +		return
log.Fatal() は終了コードが 0 以外でプログラムを終了させるから return はいらない

2021-09-24 16:39 UTC, earlgray283 commented on pkg/db/controller.go
> +func DBContoroller(toDo model.ToDo, id string, methods string) ([]model.Homework, error) { //戻り値の[]model.HomeworkはfetchAllHomeworkのためだけにあります。
この設計、よく考えたとは思うけどあまりよろしくない気がする。理由は以下の通り
- HandleFunc でハンドラを登録する意味がなくなってしまう
- NewController() で db を何度も生成してしまっている(db への接続のコストとかリソースのコストとかが厳しい)
- 同じメソッドで別の api が必要となったときに対応が難しい

ということで、基本的には ApiClient みたいなので Controller を wrap して、ハンドラはそのメソッドにするのがいいと思う(material-gakujo でそれっぽいことしてたような気がする)

2021-09-24 16:39 UTC, earlgray283 commented on pkg/server/http.go
> +func fetchAllHomework(w http.ResponseWriter, r *http.Request) {
こういうのを ApiClient のメソッドにすれば良い

2021-09-24 16:39 UTC, earlgray283 commented on pkg/server/http.go
> +	fetchHomework, err := db.DBContoroller(model.ToDo{}, "", http.MethodGet)
DBContoller っていう名前だと何をする関数なのかがわからないという問題点もある

2021-09-24 16:39 UTC, earlgray283 commented on pkg/server/http.go
> +	fetchHomework, err := db.DBContoroller(model.ToDo{}, "", http.MethodGet)
あと、fetchHomework は一般に関数名っぽいから homework とかシンプルにした方が良さそう。fetch を強調したいなら形容詞にするとか

2021-09-24 16:39 UTC, earlgray283 commented on pkg/server/http.go
> +	json.NewEncoder(w).Encode(fetchHomework)
Encode() では fetchHomework のアドレスを渡した方が良い。理由は構造体の値を渡してしまうとコピーが渡されてしまうから、メモリの無駄になっちゃうので

2021-09-24 16:39 UTC, earlgray283 commented on pkg/server/http.go
> +		http.Error(w, "Worning!!\nThis Id number couldn't be updated\nThere is a possibility that the id you entered is wrong.\nPlease check the id ", http.StatusInternalServerError)
warning?

2021-09-24 16:39 UTC, earlgray283 commented on pkg/server/http.go
> +	// router.HandleFunc("/todo/{id}", fetchSinglehHomework).Methods("GET") 1つだけ取得したい時ってあるのかな？
まあ TODO だとないかな？
でも、詳細情報と概要情報で TODO を分けてるなら1つだけ取得したいと思う。

ってなったときに、今の DBContoroller() は対応が難しいと思う。

2021-09-24 16:39 UTC, earlgray283 commented on pkg/server/http.go
> +	router.HandleFunc("/todo", setHomework).Methods("POST")
Content-Type を制限しておきたいね

2021-09-24 17:26 UTC, kajikaji0725 commented on pkg/db/controller.go
> +func DBContoroller(toDo model.ToDo, id string, methods string) ([]model.Homework, error) { //戻り値の[]model.HomeworkはfetchAllHomeworkのためだけにあります。
上位ディレクトリのパッケージのメソッドって下位ディレクトリのパッケージでも使えるの？

2021-09-25 05:19 UTC, kajikaji0725 commented on pkg/server/http.go
> +		http.Error(w, "Worning!!\nThis Id number couldn't be updated\nThere is a possibility that the id you entered is wrong.\nPlease check the id ", http.StatusInternalServerError)
！！！１
中級英語頑張ります

2021-09-25 06:38 UTC, merged